# Generated by Django 3.0.7 on 2020-06-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('item', models.CharField(max_length=150, verbose_name='Item')),
                ('check', models.BooleanField(default=False, verbose_name='Checar')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Decoration',
                'verbose_name_plural': 'Decorations',
            },
        ),
        migrations.CreateModel(
            name='PanTeaGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Pan Tea Guest',
                'verbose_name_plural': 'Pan Tea Guests',
            },
        ),
        migrations.CreateModel(
            name='PanTeaOrganizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('soda_quantity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Soda Quantity')),
                ('diet_soda_quantity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Diet Soda Quantity')),
                ('juice_quantity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Juice Quantity')),
                ('diet_juice_quantity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Diet Juice Quantity')),
                ('food_cook', models.CharField(blank=True, max_length=50, null=True, verbose_name='Food Cook')),
                ('how_to_get_the_food', models.CharField(blank=True, max_length=100, null=True, verbose_name='How to Get The Food')),
                ('food_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Food Price')),
                ('food_ready', models.BooleanField(default=False, verbose_name='Food Ready')),
                ('drinks_ready', models.BooleanField(default=False, verbose_name='Drinks Ready')),
            ],
            options={
                'verbose_name': 'Pan Tea Organizer',
                'verbose_name_plural': 'Pan Tea Organizers',
            },
        ),
    ]
