# Generated by Django 3.0.7 on 2020-08-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantea', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decoration',
            options={'verbose_name': 'Decoração', 'verbose_name_plural': 'Decorações'},
        ),
        migrations.AlterModelOptions(
            name='panteaguest',
            options={'verbose_name': 'Convidado do Chá de Panela', 'verbose_name_plural': 'Convidados do Chá de Panela'},
        ),
        migrations.AlterModelOptions(
            name='panteaorganizer',
            options={'verbose_name': 'Organizador do Chá de Panela', 'verbose_name_plural': 'Organizadores do Chá de Panela'},
        ),
        migrations.AlterField(
            model_name='panteaorganizer',
            name='diet_juice_quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quant. de Suco Diet'),
        ),
        migrations.AlterField(
            model_name='panteaorganizer',
            name='diet_soda_quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quant. de Refrigerantes Diet'),
        ),
        migrations.AlterField(
            model_name='panteaorganizer',
            name='drinks_ready',
            field=models.BooleanField(default=False, verbose_name='Bebidas Pronto'),
        ),
        migrations.AlterField(
            model_name='panteaorganizer',
            name='food_cook',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cozinheiro'),
        ),
        migrations.AlterField(
            model_name='panteaorganizer',
            name='food_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Preço da Comida'),
        ),
        migrations.AlterField(
            model_name='panteaorganizer',
            name='food_ready',
            field=models.BooleanField(default=False, verbose_name='Comida Pronto'),
        ),
        migrations.AlterField(
            model_name='panteaorganizer',
            name='how_to_get_the_food',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Como pegar a comida'),
        ),
        migrations.AlterField(
            model_name='panteaorganizer',
            name='juice_quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quant. de Suco'),
        ),
        migrations.AlterField(
            model_name='panteaorganizer',
            name='soda_quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quant. de Refrigerante'),
        ),
    ]
