# Generated by Django 3.0.7 on 2020-06-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_auto_20200614_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default='quarto 7', max_length=100, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
