# Generated by Django 3.0.7 on 2020-06-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_auto_20200614_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(default=1, max_length=100, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
