# Generated by Django 3.0.7 on 2020-08-02 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_auto_20200614_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Apartamento', 'verbose_name_plural': 'Apartamentos'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Despesa', 'verbose_name_plural': 'Despesas'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Quarto', 'verbose_name_plural': 'Quartos'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='apartment',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='contact',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='couple_grade',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Nota do Casal'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='distance_to_bus_stop',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Distância até o Ponto de Ônibus'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='distance_to_essential_places',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Distância até Estabelecimentos Essenciais'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='distance_to_subway',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Distância até o Metrô'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='num_bathrooms',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Número de Banheiros'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='num_rooms',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Número de Quartos'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='apartment_photos', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='system_grade',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Nota do Sistema'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='item',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.Room', verbose_name='Quarto'),
        ),
        migrations.AlterField(
            model_name='item',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Preço (Tt.)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Preço (Un.)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='urgency',
            field=models.CharField(choices=[('ES', 'Essencial'), ('IM', 'Importante'), ('DE', 'Adiável')], default='ES', max_length=10, verbose_name='Urgência'),
        ),
    ]
