# Generated by Django 3.0.7 on 2020-08-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_auto_20200802_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='total_price',
        ),
    ]
