# Generated by Django 3.0.7 on 2020-06-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('hotel_name', models.CharField(max_length=150, verbose_name='Hotel Name')),
                ('hotel_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Hotel Price')),
                ('tickets_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Tickets Price')),
                ('leave_date', models.CharField(blank=True, max_length=200, null=True, verbose_name='Leave Date')),
                ('arrival_date', models.CharField(blank=True, max_length=200, null=True, verbose_name='Arrival Date')),
                ('tour_company', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tour Company')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
            },
        ),
        migrations.CreateModel(
            name='HoneymoonOrganizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('when', models.DateField(blank=True, null=True, verbose_name='When')),
                ('how_long', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='How many days')),
                ('where', models.CharField(blank=True, max_length=200, null=True, verbose_name='Where')),
                ('script', models.FileField(blank=True, null=True, upload_to='honeymoon_scripts', verbose_name='Tour Script')),
            ],
            options={
                'verbose_name': 'Honeymoon Organizer',
                'verbose_name_plural': 'Honeymoon Organizers',
            },
        ),
    ]
