# Generated by Django 3.0.7 on 2020-08-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeymoon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name': 'Orçamento', 'verbose_name_plural': 'Orçamentos'},
        ),
        migrations.AlterModelOptions(
            name='honeymoonorganizer',
            options={'verbose_name': 'Organizador de Lua de Mel', 'verbose_name_plural': 'Organizadores de Lua de Mel'},
        ),
        migrations.AlterField(
            model_name='budget',
            name='arrival_date',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Data de Chegada'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='hotel_name',
            field=models.CharField(max_length=150, verbose_name='Nome do Hotel'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='hotel_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Preço do Hotel'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='leave_date',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Data de Partida'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='tickets_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Preço das Passagens'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='tour_company',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Cia. Turística'),
        ),
        migrations.AlterField(
            model_name='honeymoonorganizer',
            name='how_long',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quantos dias'),
        ),
        migrations.AlterField(
            model_name='honeymoonorganizer',
            name='script',
            field=models.FileField(blank=True, null=True, upload_to='honeymoon_scripts', verbose_name='Script do Tour'),
        ),
        migrations.AlterField(
            model_name='honeymoonorganizer',
            name='when',
            field=models.DateField(blank=True, null=True, verbose_name='Quando'),
        ),
        migrations.AlterField(
            model_name='honeymoonorganizer',
            name='where',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Onde'),
        ),
    ]
