# Generated by Django 3.0.7 on 2020-08-02 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ceremony', '0002_auto_20200605_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ceremony',
            options={'verbose_name': 'Cerimônia', 'verbose_name_plural': 'Cerimônias'},
        ),
        migrations.AlterModelOptions(
            name='clothesplanner',
            options={'verbose_name': 'Planejador de Vestimentas', 'verbose_name_plural': 'Planejadores de Vestimentas'},
        ),
        migrations.AlterModelOptions(
            name='groomsman',
            options={'verbose_name': 'Padrinho', 'verbose_name_plural': 'Padrinhos'},
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': 'Convidado', 'verbose_name_plural': 'Convidados'},
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name': 'Música', 'verbose_name_plural': 'Músicas'},
        ),
        migrations.AlterModelOptions(
            name='occasion',
            options={'verbose_name': 'Ocasião', 'verbose_name_plural': 'Ocasiões'},
        ),
        migrations.AlterField(
            model_name='ceremony',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='ceremony',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='clothesplanner',
            name='brides_body_accessories',
            field=models.FileField(blank=True, null=True, upload_to='clothes_planner', verbose_name='Acessórios de Corpo da Noiva'),
        ),
        migrations.AlterField(
            model_name='clothesplanner',
            name='brides_dress',
            field=models.FileField(blank=True, null=True, upload_to='clothes_planner', verbose_name='Vestido da Noiva'),
        ),
        migrations.AlterField(
            model_name='clothesplanner',
            name='brides_hair_accessories',
            field=models.FileField(blank=True, null=True, upload_to='clothes_planner', verbose_name='Acessórios de Cabelo da Noiva'),
        ),
        migrations.AlterField(
            model_name='clothesplanner',
            name='brides_hairstyle',
            field=models.FileField(blank=True, null=True, upload_to='clothes_planner', verbose_name='Pentado da Noiva'),
        ),
        migrations.AlterField(
            model_name='clothesplanner',
            name='brides_lingerie',
            field=models.FileField(blank=True, null=True, upload_to='clothes_planner', verbose_name='Lingerie da Noiva'),
        ),
        migrations.AlterField(
            model_name='clothesplanner',
            name='brides_makeup',
            field=models.FileField(blank=True, null=True, upload_to='clothes_planner', verbose_name='Maquiagem da Noiva'),
        ),
        migrations.AlterField(
            model_name='clothesplanner',
            name='brides_mom_dress_color',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Cor do Vestido da Mãe da Noiva'),
        ),
        migrations.AlterField(
            model_name='clothesplanner',
            name='brides_shoes',
            field=models.FileField(blank=True, null=True, upload_to='clothes_planner', verbose_name='Sapatos da Noiva'),
        ),
        migrations.AlterField(
            model_name='clothesplanner',
            name='grooms_mom_dress_color',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Cor do Vestido da Mãe do Noivo'),
        ),
        migrations.AlterField(
            model_name='clothesplanner',
            name='grooms_shoes',
            field=models.FileField(blank=True, null=True, upload_to='clothes_planner', verbose_name='Sapatos do Noivo'),
        ),
        migrations.AlterField(
            model_name='clothesplanner',
            name='grooms_suit',
            field=models.FileField(blank=True, null=True, upload_to='clothes_planner', verbose_name='Terno do Noivo'),
        ),
        migrations.AlterField(
            model_name='clothesplanner',
            name='kids_dress_color',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Cor do Vestido das Damas de Honra'),
        ),
        migrations.AlterField(
            model_name='clothesplanner',
            name='ring_bearer_costume_color',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Cor da Vestimenta do Pajem'),
        ),
        migrations.AlterField(
            model_name='groomsman',
            name='duo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ceremony.Groomsman', verbose_name='Par'),
        ),
        migrations.AlterField(
            model_name='groomsman',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='groomsman',
            name='selector',
            field=models.CharField(choices=[('GR', 'Noivo'), ('BR', 'Noiva')], default='BR', help_text='Quem escolheu o noivo', max_length=6, verbose_name='Apadrinhado'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='group',
            field=models.CharField(choices=[('GFA', 'Família do Noivo'), ('BFA', 'Família da Noiva'), ('GFR', 'Amigo do Noivo'), ('BFR', 'Amigo da Noiva'), ('UNW', 'Não quero convidar, mas preciso')], max_length=40, verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='indispensability',
            field=models.PositiveSmallIntegerField(help_text='Indica o quanto você realmente quer que essa pessoa vá', verbose_name='Indispensabilidade'),
        ),
        migrations.AlterField(
            model_name='music',
            name='duration',
            field=models.TimeField(blank=True, null=True, verbose_name='Duração da Música'),
        ),
        migrations.AlterField(
            model_name='music',
            name='link',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Link para a música'),
        ),
        migrations.AlterField(
            model_name='music',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Song Name'),
        ),
        migrations.AlterField(
            model_name='music',
            name='occasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ceremony.Occasion', verbose_name='Ocasião'),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ocasião'),
        ),
    ]
